name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile CSS and Javascript
        run: |
          npm ci
          npm run prod

      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
          extensions: php-cli, php-common, php-fpm, php-mysql, php-zip, php-gd, php-mbstring, php-curl, php-xml, php-bcmath, openssl, php-json, php-tokenizer

      - name: Composer install
        run: |
          composer install --no-dev --no-interaction --prefer-dist